GLOSSARY = list(
  ISA = "Interchange Control Header — envelope opener; identifies sender, receiver, date, time, and control number",
  IEA = "Interchange Control Trailer — closes the ISA envelope; contains group count and control number",
  GS = "Functional Group Header — groups related transactions; GS01=HC for 837 claims, GS01=RA for 835 remittance",
  GE = "Functional Group Trailer — closes the GS functional group; contains transaction set count",
  ST = "Transaction Set Header — begins the transaction; ST01=837 for claims, ST01=835 for remittance advice",
  SE = "Transaction Set Trailer — ends the transaction; SE01 must match actual segment count between ST and SE",
  BPR = "Beginning of Payment — total payment amount, payment method, and banking/ACH routing details for the remittance",
  TRN = "Reassociation Trace Number — unique identifier linking this 835 remittance to the corresponding EFT payment",
  DTM_405 = "Payment Date — the date on which the remittance payment was issued by the payer",
  NM1_85 = "Billing Provider — name, entity type (1=individual, 2=organization), and NPI of the provider submitting the claim",
  NM1_87 = "Pay-to Provider — alternate name and address where payment should be remitted",
  NM1_IL = "Subscriber (Insured) — the policyholder named on the insurance plan",
  NM1_QC = "Patient — the individual who received the services; last and first name are required",
  NM1_PR = "Payer — the insurance company or health plan receiving the claim or issuing remittance",
  NM1_PE = "Payee — the provider or organization receiving the remittance payment",
  NM1 = "Name Segment — entity name, identifier type, and ID number",
  N1_PR = "Payer Name Loop — identifies the insurance company issuing the 835 remittance",
  N1_PE = "Payee Name Loop — identifies the provider receiving the 835 remittance payment",
  CLM = "Claim Information — patient control number, total charge amount, and place/type of service",
  CL1 = "Institutional Claim Code — admission type, admission source, and patient discharge status; required for 837I",
  CLP = "Claim Payment Information — patient control number, claim status, billed amount, and paid amount per claim",
  CAS = "Claim/Service Adjustment — group code, reason code, and dollar amount explaining differences between billed and paid",
  SVD = "Service Line Adjudication — service-level payment detail within a remittance 835 transaction",
  PLB = "Provider Level Balance — provider-level payment adjustments applied across the entire remittance",
  DTP_472 = "Date of Service — the date or date range on which professional services were rendered",
  DTP_435 = "Admission Date — date the patient was admitted; required for 837I inpatient institutional claims",
  DTP_434 = "Discharge Date — date the patient was discharged from the facility",
  DTP_431 = "Onset of Current Illness Date — date of first symptom or injury related to this claim",
  DTP = "Date/Time Reference — various date fields identified by qualifier in DTP01",
  SV1 = "Professional Service Line — CPT/HCPCS procedure code with HC qualifier, charge amount, units, and diagnosis pointers",
  SV2 = "Institutional Service Line — revenue code + HCPCS procedure, charge amount, and units for hospital/facility claims",
  REF = "Reference Identification — prior authorization numbers, referral IDs, or payer-required reference data",
  HI = "Health Care Diagnosis Codes — ICD-10-CM diagnosis codes supporting the claim (ABK=principal diagnosis)",
  LX = "Service Line Number — sequential counter identifying each service line within the claim",
  PRV = "Provider Information — provider specialty taxonomy code",
  SBR = "Subscriber Information — insurance plan details for the subscriber",
  PAT = "Patient Information — patient relationship to subscriber and other patient details",
  PER = "Administrative Contact — contact person name and phone/fax/email for the provider",
  N3 = "Address Information — street address line",
  N4 = "Geographic Location — city, state, and ZIP code",
  AMT = "Monetary Amount — various monetary amounts (e.g., approved, patient responsibility)",
  QTY = "Quantity — quantity information for the service or claim",
  MOA = "Medicare Outpatient Adjudication — Medicare-specific adjudication data"
)
