list(
  "14" = "Master Account Number",
  "17" = "Client Reporting Category",
  "18" = "Plan Number",
  "23" = "Client Number",
  "38" = "Master Policy Number",
  "60" = "Cross Reference Number",
  "72" = "Schedule Reference Number",
  "0F" = "Subscriber Number",
  "1D" = "",
  "1L" = "Group or Policy Number",
  "1W" = "Member Identification Number",
  "2F" = "Consolidated Invoice Number",
  "3H" = "Case Number",
  "4A" = "Personal Identification Number (PIN)",
  "6P" = "",
  "D3" = "NCPDP Pharmacy Number",
  "F6" = "HIC Number (Health Insurance Claim)",
  "P5" = "Position Code",
  "Q4" = "Prior Identifier Number",
  "9V" = "",
  "AZ" = "Health Insurance Policy Number",
  "CE" = "",
  "DX" = "Department/Agency Number",
  "LB" = "Lockbox",
  "RB" = "",
  "TV" = "Line of Business",
  "QQ" = "Unit Number",
  "ZX" = "",
  "ZZ" = "Mutually Defined",
  "ABB" = "Personal ID Number",
  "ABY" = "CMS PlanID",
  "POL" = "Policy Number"
)

# These are all X12-850
# BEG00 = perl(x, r"(BEG\*00)"),
# BEG24 = perl(x, r"(BEG\*24)"),
# CTT = perl(x, "^CTT"),
# N12L = perl(x, r"(N1\*2L)"),
# N1BY = perl(x, r"(N1\*BY)"),
# N1ST = perl(x, r"(N1\*ST)"),
# PERBD = perl(x, r"(PER\*BD)"),
# PERSR = perl(x, r"(PER\*SR)"),
# PID = perl(x, r"(PID)"),
# PO1 = perl(x, r"(PO1)"),
# REFDP = perl(x, r"(REF\*DP)"),
# REFK6 = perl(x, r"(REF\*K6)"),
